# -*- coding: utf-8 -*-
"""11. Data Cleaning Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TrAytnhH2jLTcYMbdKMDtqh0tzASyaz
"""

import pandas as pd
import numpy as np

# Reading Our Dataset

data = pd.read_csv('/content/diabetes.csv')

data.head()

# Total Rows & Columns

data.shape

# Basic Statistics

data.describe()

"""**Replacing 0 with Nan**"""

# All columns

columns = list(data)
columns

# Checking Null Values

data.isnull().sum()

# Calculating Total Zeros in Glucose, BloodPressure, SkinThickness, Insulin and BMI

(data[columns[1:6]] == 0).sum()

# Replace Statement

data[columns[1:6]] = data[columns[1:6]].replace(0,np.nan)

# Again Checking Null Values

data.isnull().sum()



"""**Drop Empty Rows**"""

# Before Drop Statement

data.shape

# Drop Statment

data.dropna(inplace = True)

# After Drop Statement

data.shape

768/2

768-392



"""# Dealing With Missing Values

Imputation Techniques
*   Mean , Median , Mode
"""

data = pd.read_csv('/content/CompanyProfit.csv')
data2 = pd.read_csv('/content/CompanyProfit_new.csv')
data3 = pd.read_csv('/content/CompanySuccess.csv')

data.head(10)

# Checking Empty Values

data.isnull().sum()

import seaborn as sns

# Distribution Plot to identify Which Technique to use

sns.distplot(data['Profit ($)'])

# # Fillna Method Using Mean

col = data['Profit ($)']

col = col.fillna(col.mean(), inplace = True)

# After Fillna Method

data.isnull().sum()

data.head(20)



"""**Median Technique**"""

data2.isnull().sum()

# Distribution Plot to identify Which Technique to use

sns.distplot(data2['Profit ($)'])

# # Fillna Method Using Median

col = data2['Profit ($)']

col = col.fillna(col.median(), inplace = True)

# After Fillna Method

data2.isnull().sum()



"""**Conclusion**"""

# Mean - For Normal Distribution
# Median - Right or Left Skewed Data   (Not Normal Distribution)







"""**Mode Techinque**"""

data3.head(20)

data3.isnull().sum()

# # Fillna Method Using Mean, Median

# col = data3['Success']

 # col = col.fillna(col.mean(), inplace = True)

# # Fillna Method Using Mode

col = data3['Success']

col = col.fillna(col.mode()[0], inplace = True)

data3.isnull().sum()

