# -*- coding: utf-8 -*-
"""Python Basics Day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVZQGT3hIqiaRTbzLoPDjgdqtMzfMKKm

# For Loop

*   It is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).
*   Using Break & Contiue keyword
"""

fruits = ["apple", "banana", "cherry",'pineappple','mango']

for i in fruits:
  print(i)





for x in fruits:
  print(x)
  if x == "banana":
    break

for x in fruits:
  if x == "cherry":
    continue
  print(x)





"""# While Loop

*   With the while loop we can execute a set of statements as long as a condition is true.
*   Using Break & Contiue keyword
"""

num = 1

while num < 6:
  print(num)
  num += 1

num = 1

while num < 6:
  print(num)
  if num == 3:
    break
  num = num + 1





num = 0

while num < 10:
  num += 1
  if num == 5:
    continue
  print(num)





"""# Python Functions

*   A function is a block of code which only runs when it is called.

*   Advanced Functions - lambda, map, zip
"""

def intro():                     # Function Defining
  value = 5
  return value**2
  # print("Hello i'm from a function")

intro()       # Function Calling

def my_ID(name):                    # Function with Arguments
  print("CR001_" + name)

my_ID("Sai")

# def add(a,b,c):
#   return a+b+c


# Using Lambda Function

add = lambda a,b,c: print(a+b+c)

add(4, 5, 5)

# add(4,5,1)

# Map Function

nums = [1, 2, 3, 4, 5]

def sq(n):
    return n*n

# sq(2)

square = map(sq, nums)

print(list(square))

# Zip Function

name = ["Manjeet", "Nikhil", "Shambhavi"]
ID = [4, 1, 3]

mapped = zip(name, ID)

print(list(mapped))

type(mapped)

