# -*- coding: utf-8 -*-
"""Python Basics Day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5IfO2EYHUNMxLljcUmnwzvyMJeLAVHe

**Python Basic Terms**


*   Syntax (Valid & Invalid)
*   Comments
"""

address = 'Pimpri Chinchwad, Pune : 411057'    # This is my address
print(address)                                # This is the print statement

print('Pune')



address



"""**Python Data Types, Type Casting & Variables**


*   **Text Type:**	str
*   **Numeric Types:**	int, float
*   **Sequence Types:**	list, tuple, range
*   **Mapping Type:**	dict
*   **Set Types:**	set
*   **Boolean Type:**	bool



"""

name = 'Mohit'
age = 25
height = 5.8

profile = ['Mohit',25,5.8,60,'Engineer']         # List Method
profile_2 = ('Disha',23,5.5,55,'Teacher')        # Tuple Method
profile_3 = {'Name':'Sai','Role':'Cricket Analyst','age':22,'City':'Pune'} # Dictionary Method
profile_4 = {'Sreedevi',55.6,'Teacher', 5.6}     # Set Method

print(profile_4)

type(profile_4)

student1 = ('Rishika', 21, 90.2)    # Cannot modify it
student2 = ['Rishika', 21, 90.2]    # Can modify it
student3 = {'Rishika', 21, 90.2}    # Random Output

type(student3)

student = {'Name':'Rishika', 'Age': 21, 'Percent':90.2}

bool(1)

age = str(22)

type(age)





"""**Python Operators**

*   Arithmetic operators
*   Assignment operators
*   Comparison operators
*   Logical operators
*   Membership operators
"""

# Arithmetic Operators (+,-,*,/,%,**)                        # Used with numeric values to perform common mathematical operations

x = 5
y = 8

# print(x+y, x-y, x*y, x/y, x%y, x**y)

print(x*y)

# Assignment Operators (=,+=,-=,*=,/=,%=,**=)                # Used to assign values to variables

x, y = 5, 8


# x = x - y
# x -= y       # x = x - y/


x = x * y


print(x)

# Comparison Operators (==,!=,<,>,<=,>=)                     # Used to compare two values

# print(x == y, x != y, x < y, x > y, x <= y, x >= y)
x, y = 5, 8

x >= y

# Logical Operators (==,!=,<,>,<=,>=)                        # Used to combine conditional statements

# print(x and y)

case1 =(x < y) or (x == y)

print(case1,not(case1))

# Membership Operators (==,!=,<,>,<=,>=)                     # Used to test if a sequence is presented in an object

# print(x in y, x not in y)

x = [1,2,3,4,5]
y = 6

y not in x



