# -*- coding: utf-8 -*-
"""Python Basics Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0uq4qwhsoT1TZ2-dSUx2ypelf67Y5Do

# List and it's Methods

Lists are used to store multiple items in a single variable.

*   Lists are used to store multiple items in a single variable.
*   It is a collection which is ordered, changeable and allows duplicate members.

**List Methods**


append(), sort(), reverse(), remove(), pop(), insert(), index(), extend(), count(), copy(), clear()
"""

# fruits = ['apple', 'cherry', 'banana']

# fruits.append("orange")
# fruits.sort()
# fruits.reverse()
# fruits.remove("banana")
# fruits.pop(1)
# fruits.insert(1, "watermelon")
# fruits.index("orange")

# others = ['pineapple', 'strawaberry', 'guava','cherry','pineapple']

# fruits.extend(others)
# fruits.count("cherry")
# fruits.copy()
# fruits.clear()

# fruits

# fruits.pop(0)

# fruits_2









"""# String and it's Methods

*   All string methods returns new values. They do not change the original string.

**String Methods**


*   isalpha(), isalnum(), index(), find(), count(), capitalize(), isdigit(), islower(), isnumeric()
*   endswith(), upper(), title(), swapcase(), strip(), startswith(), split(), join(), lower(), replace()
"""

txt = "hello, and welcome to our course."
a = txt.capitalize()
# print(a)

txt = "I am from India and born in Maharashtra, India"
b = txt.count("India")
# print(b)

txt = "I love apples, apple are my favorite fruit"
c = txt.find("banana")
# print(c)

# d = txt.index("banana")
# print(d)

txt = "hello, my name is Peter, I am 26 years old"
e = txt.split(',')
print(e)







txt = "I love apples, apple is my favorite fruit"

txt.find('banana')

txt.index('banana')









txt = "Company12"
name = txt.isalnum()
# print(name)

txt = "Company"
alpha = txt.isalpha()
# print(alpha)

txt = '50800'
num = txt.isdigit()
# print(num)

names = ["John", "Peter", "Vicky"]
joined = "_".join(names)
# print(joined)

txt = "I love sports"
result = txt.replace("sports", "cricket")
print(result)

txt = "Hello, welcome to my world."
start = txt.startswith("Hello")
end = txt.endswith(".")

start, end



"""# Python Conditional Statements


*   If , elif, else statements
"""

b , a = 33 , 200

# print(b>a)

if b > a:
  print("Entered")
else:
  print('Did not entered')

aman , vinod = 90 , 80

if vinod > aman:
  print("vinod scores greater than aman")
elif aman == vinod:
  print("Both scores equally")

if vinod > aman:
  print("vinod scores greater than aman")
elif aman == vinod:
  print("Both scores equally")
else:
  print('aman scores greater than vinod')

marks = 72

if marks > 35:
  print("He is Pass")
  if marks > 60:
    print("He is in Distinction")
  else:
    print("He is in Mid Range")
else:
  print('Sadly, He is Fail')



